# Generated by Django 4.1.2 on 2023-01-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_to_speech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speechfile',
            name='mp3',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='speechfile',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
